# used to extract the version from a release branch
# "release/1.0.0-next.0" -> "1.0.0-next.0"
name: extract-version-from-branch
description: Extracts version from a branch name
inputs:
  branch:
    description: branch name (e.g. head_ref)
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: true
    - uses: .github/actions/extract-version-from-branch
      with:
        branch: ${{ github.head_ref }}
    - name: delete-release-branch
      run: git push origin --quiet --delete ${{ inputs.branch }} && echo 'deleted branch' || true
      shell: bash
    - name: delete-release-draft
      run: gh release delete ${{ steps.version.outputs.result }} && echo 'deleted release' || true
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
