# used to extract the version from a release branch
# "release/1.0.0-next.0" -> "1.0.0-next.0"
name: extract-version-from-branch
description: Extracts version from a branch name
inputs:
  branch:
    description: branch name (e.g. head_ref)
    required: true
outputs:
  version:
    description: extracted version
    value: ${{ steps.version.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: extract-version
      id: version
      uses: actions/github-script@v6
      with:
        script: |
          return context.inputs.branch.replace(/release\: /, '');
        result-encoding: string
