name: cleanup-discarded-release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  cleanup:
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    uses: .github/actions/cleanup-discarded-release
    with:
      branch: ${{ github.head_ref }}
