name: closed-release-cleanup
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  cleanup:
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    uses: ./.github/workflows/reusable/cleanup-discarded-release.yaml
    with:
      branch: ${{ github.head_ref }}
