name: create-release-branch
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: 'Type of release'
        options:
          - major
          - minor
          - patch
          - prerelease
        required: true
      # version:
      #   description: 'Version to deploy (i.e. 0.8.0)'
      #   required: true
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v2.2.2
      - name: set-version
        id: version
        run: |
          if [ ${{ github.event.inputs.type }} != prerelease ]
          then
            echo "::set-output name=version::pnpm version ${{ github.event.inputs.type }} --no-git-tag-version)"
          else
            echo "::set-output name=version::pnpm version ${{ github.event.inputs.type }} --no-git-tag-version --preid next)"
          fi
      - run: echo "::notice title="releasing"::${{ steps.version.output.version }}"
      # - uses: actions/setup-node@v3  # is this needed???
      #   with:
      #     node-version-file: '.nvmrc'
      #     cache: 'pnpm'
      # get version
      # - run: echo ::set-output
      - id: branch
        run: echo "::set-output name=name::release/v${{ steps.version.output.version }}"
      - name: Create release branch
        run: git checkout -b ${{ steps.branch.output.name }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git add package.json
          git commit -m '[automated] release ${{ steps.version.output.version }}'
      - run: git push origin ${{ steps.branch.output.name }}
# bumps version with `pnpm version...` (should this create the tag???)
# if pnpm creates the tag, we need to push it to git _before_ running `gh release create...` to mitigate clashing version tags
# or can set this to false https://docs.npmjs.com/cli/v8/commands/npm-version#git-tag-version
