name: pr-has-semver-label
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - labeled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-has-semver-label:
    name: pr-has-semver-label
    runs-on: ubuntu-latest
    strategy:
      matrix:
        semver-label:
          - 'semver:\ major'
          - 'semver:\ minor'
          - 'semver:\ patch'
    steps:
      - if: contains(github.event.pull_request.labels.*.name, ${{ matrix.semver-label }})
        run: exit 0
