name: pr-has-semver-label
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled
      - ready_for_review
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-has-semver-label:
    if: github.event.pull_request.draft == false
    name: pr-has-semver-label
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/does-pr-have-semver-label
