name: pr-has-semver-label
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - labeled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-has-semver-label:
    name: pr-has-semver-label
    runs-on: ubuntu-latest
    steps:
      - if: startsWith(github.event.pull_request.labels.*.name, 'semver')
        run: exit 0
      - run: exit 1
