name: pr-has-semver-label
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - labeled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-has-semver-label:
    name: pr-has-semver-label
    runs-on: ubuntu-latest
    steps:
      - if: |
          contains(github.event.pull_request.labels.*.name, 'semver: major') || 
          contains(github.event.pull_request.labels.*.name, 'semver: minor') || 
          contains(github.event.pull_request.labels.*.name, 'semver: patch')
        run: exit 0
      - if: '!success()'
        run: exit 1
