name: release-env
on:
  workflow_call:
    inputs:
      env:
        description: 'Application environment (e.g. "next")'
        type: string
        required: true
      version:
        description: 'Version of the release'
        type: string
        required: true
      is-prerelease:
        description: 'Determines if the release is a prerelease'
        type: boolean
        required: true
jobs:
  release-env:
    runs-on: ubuntu-latest
    environment: ${{ github.events.inputs.env }}
    permissions:
      contents: write # for gh CLI to create a release
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: cdk synth
        run: |
          pnpm cdk synth \
            --context env=${{ github.events.inputs.env }} \
            --context version=${{ github.events.inputs.version }}
      - name: cdk deploy
        run: |
          pnpm cdk deploy \
            --context env=${{ github.events.inputs.env }} \
            --context version=${{ github.events.inputs.version }}
      - name: release
        run: |
          if [ ${{ github.event.inputs.is-prerelease }} == true ]
          then
            url=$(gh release create ${{ github.events.inputs.version }} --generate-notes --prerelease)
          else
            url=$(gh release create ${{ github.events.inputs.version }} --generate-notes)
          fi
          tag=$(echo "${url/releases\/tag/tree}")
          echo ::notice title="release"::$url
          echo ::notice title="tag"::$tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
