name: release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - run: echo "${{ github.event.pull_request.head.ref }}"
      - run: echo "${{ github.event.pull_request.base.ref }}"
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.pull_request.title.replace(/release\: /, '');
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: prerelease
        if: ${{ contains(steps.tag.outputs.result, 'next') }}
        run: gh release create ${{ steps.tag.outputs.result }} --generate-notes --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        if: ${{ !contains(steps.tag.outputs.result, 'next') }}
        run: gh release create ${{ steps.tag.outputs.result }} --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# https://github.com/orgs/community/discussions/26686#discussioncomment-3252850
