name: release
on:
  pull_request:
    branches:
      - 'release/**'
      - main
    types:
      - closed
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - run: echo "${{ github.event.pull_request.head.ref }}"
      - run: echo "${{ github.event.pull_request.base.ref }}"
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.pull_request.title.replace(/release\: /, '');
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - if: ${{ contains(steps.tag.outputs.result, 'next') }}
        run: echo 'NEXT'
      - if: ${{ !contains(steps.tag.outputs.result, 'next') }}
        run: echo "PRODUCTION"
      # - run: 'gh release create --target ${{ github.event.pull_request.head.ref }}'
# https://github.com/orgs/community/discussions/26686#discussioncomment-3252850
