name: release
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - id: version
        run: echo ::set-output name=version::${{ github.event.ref }}
      - run: echo "::debug::${{ steps.version.outputs.version }}"
      - if: ${{ steps.version.outputs.version }}
        run: echo 'yes'
      - if: contains(steps.version.outputs.version, 'next')
        run: echo 'yes'
      - if: contains(${{ steps.version.outputs.version }}, 'next')
        run: echo 'yes'
      # - run: 'gh release create --target ${{ github.event.pull_request.head.ref }}'
